---


global:
  pollFrequency: 5m #how often to refresh
  sshKeyPath: id-rsa
  publicAddress: https://gitthing.myorg.com

providers:
- name: github
  org: example-org

repos:
- url: git@github.com:k8s-wtf/gitthing-example.git
  path: /             # subdirectory to hash
  sshKeyPath: id-rsa
  pollFrequency: 1m   # over-ride global

